using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Andersoft.Messaging.Generator;

/// <summary>
/// Generates a strongly-typed dispatcher and DI registration from the message handlers
/// in the compilation. There are no message marker interfaces: everything is inferred
/// from the handler declarations.
///
/// <list type="bullet">
/// <item><c>IMessageHandler&lt;TMessage, TResult&gt;</c> ⇒ a single-dispatch message that
/// returns a value (<c>DispatchAsync</c> returns <c>ValueTask&lt;TResult&gt;</c>).</item>
/// <item><c>IMessageHandler&lt;TMessage&gt;</c> ⇒ a void message dispatched to <em>all</em>
/// registered handlers (one or many — "command" vs "event" is not modelled).</item>
/// <item><c>Saga&lt;TState&gt;</c> subclasses are coordinators, excluded from handler
/// discovery; each saga event gets a <c>SagaDispatcher&lt;TEvent&gt;</c> registered onto
/// that event's fan-out.</item>
/// </list>
/// </summary>
[Generator]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The consumer-facing Saga<TState> base is emitted via post-initialization so it exists in
        // the compilation BEFORE the main pipeline runs — that is what lets the semantic model bind
        // a consumer's `: Saga<TState>` and so detect sagas at all. It declares a strongly-typed
        // `TypedDispatcher Dispatcher`, which is why the base must live next to the generated
        // dispatcher (the consumer's assembly) rather than in the abstractions library.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SagaBase.g.cs", SourceText.From(SagaBaseSource, Encoding.UTF8)));

        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetHandlerTypes(ctx, ct))
            .Where(static h => h.Length > 0)
            .SelectMany<ImmutableArray<HandlerInfo>, HandlerInfo>(static (h, _) => h)
            .Collect();

        var sagas = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetSagaType(ctx, ct))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        var combined = handlers.Combine(sagas);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var allHandlers = pair.Left;

            // One saga can have several partial declarations; merge them so each saga is registered
            // exactly once. TypedDispatcher + HandlerRegistration are always emitted (even empty) so
            // the post-init Saga<TState> base's reference to TypedDispatcher always resolves.
            var sagas = MergeSagas(pair.Right);

            spc.AddSource("TypedDispatcher.g.cs",
                SourceText.From(GenerateDispatcher(allHandlers, sagas), Encoding.UTF8));
            spc.AddSource("HandlerRegistration.g.cs",
                SourceText.From(GenerateRegistration(allHandlers, sagas), Encoding.UTF8));
        });
    }

    // ── Generated Saga&lt;TState&gt; base (post-initialization, fixed text) ─────────────────────

    private const string SagaBaseSource = @"// <auto-generated />
#nullable enable
namespace Andersoft.Messaging.Abstractions.Abstractions
{
    using System;
    using System.Linq.Expressions;

    /// <summary>
    /// Typed saga base. Concrete sagas extend this and register correlations via
    /// <c>ConfigureHowToFindSaga</c>. Generated into the consumer's assembly so it can expose the
    /// generated <c>TypedDispatcher</c>; the coordinator machinery lives on the non-generic
    /// <c>Saga</c> in the abstractions library.
    /// </summary>
    public abstract class Saga<TSagaState> : Saga
        where TSagaState : SagaState, new()
    {
        /// <summary>
        /// Override to register event handlers and correlation mappings. Called once per saga type
        /// during registration. Map an event with <c>MapStartedBy</c> if it can create a new saga
        /// instance, or <c>MapHandledBy</c> if it requires an existing one. Each mapping correlates an
        /// event key to a saga-state field; the handler is the saga's
        /// <c>IMessageHandler&lt;TEvent&gt;.HandleAsync</c> implementation, bound automatically. State is
        /// available via the <see cref=""Data"" /> property.
        /// </summary>
        protected abstract void ConfigureHowToFindSaga(ISagaPropertyMapper<TSagaState> mapper);

        /// <summary>Pre-loaded saga data. Null only before any event is handled.</summary>
        protected TSagaState? Data => Accessor is SagaStateAccessor<TSagaState> a ? a.Data : null;

        /// <summary>
        /// Factory for the scoped <c>TypedDispatcher</c>, assigned during saga registration. Stored as
        /// a deferred factory rather than the resolved instance because the dispatcher's handler
        /// fan-out includes this saga: resolving it eagerly while the saga is being constructed would
        /// close a DI dependency cycle (TypedDispatcher -> SagaDispatcher -> IEnumerable&lt;Saga&gt; ->
        /// this saga -> TypedDispatcher). See <see cref=""Dispatcher"" />.
        /// </summary>
        protected internal global::System.Func<global::Andersoft.Messaging.Abstractions.TypedDispatcher> DispatcherFactory { get; internal set; } = null!;

        /// <summary>
        /// Scoped, strongly-typed dispatcher, resolved lazily on first access. Safe to use from saga
        /// handlers: by the time a handler runs the dispatcher is already fully constructed, so the
        /// deferred lookup returns that same scoped instance without re-entering construction.
        /// </summary>
        protected internal global::Andersoft.Messaging.Abstractions.TypedDispatcher Dispatcher => DispatcherFactory();

        /// <summary>Correlates events to a saga instance by matching an event key against a saga-state field.</summary>
        protected interface ISagaPropertyMapper<TState>
        {
            /// <summary>Correlates <typeparamref name=""TEvent"" /> for an event that can START a new saga
            /// instance: the instance is found by matching <paramref name=""sagaKey"" /> against
            /// <paramref name=""messageKey"" />, or created with that field initialized when none is found.
            /// <paramref name=""sagaKey"" /> must be a simple property or field.</summary>
            void MapStartedBy<TEvent, TKey>(Func<TEvent, TKey> messageKey, Expression<Func<TState, TKey>> sagaKey);

            /// <summary>Correlates <typeparamref name=""TEvent"" /> for an event that goes to an EXISTING saga
            /// instance (discarded if none is found): the instance is found by matching
            /// <paramref name=""sagaKey"" /> against <paramref name=""messageKey"" />.</summary>
            void MapHandledBy<TEvent, TKey>(Func<TEvent, TKey> messageKey, Expression<Func<TState, TKey>> sagaKey);
        }

        protected override void BuildHandlers() => ConfigureHowToFindSaga(new Mapper(this));

        private sealed class Mapper : ISagaPropertyMapper<TSagaState>
        {
            private readonly Saga<TSagaState> _saga;
            public Mapper(Saga<TSagaState> saga) => _saga = saga;

            public void MapStartedBy<TEvent, TKey>(Func<TEvent, TKey> messageKey, Expression<Func<TSagaState, TKey>> sagaKey)
                => _saga.RegisterSagaHandler<TEvent, TKey>(messageKey, sagaKey, isStartedBy: true);

            public void MapHandledBy<TEvent, TKey>(Func<TEvent, TKey> messageKey, Expression<Func<TSagaState, TKey>> sagaKey)
                => _saga.RegisterSagaHandler<TEvent, TKey>(messageKey, sagaKey, isStartedBy: false);
        }
    }
}
";

    // ── Discovery ──────────────────────────────────────────────────────

    private static ImmutableArray<HandlerInfo> GetHandlerTypes(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return ImmutableArray<HandlerInfo>.Empty;

        // Sagas are coordinators, not dispatch targets — discovered separately and
        // excluded here so they are never registered as direct message handlers.
        if (ExtendsSaga(symbol))
            return ImmutableArray<HandlerInfo>.Empty;

        var results = ImmutableArray.CreateBuilder<HandlerInfo>();

        foreach (var iface in symbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
                continue;

            var name = iface.ConstructedFrom.ToDisplayString();
            var args = iface.TypeArguments;

            switch (name)
            {
                case "Andersoft.Messaging.Abstractions.Abstractions.IMessageHandler<TMessage>":
                    results.Add(HandlerInfo.Handler(symbol.ToDisplayString(), args[0].ToDisplayString(), result: null));
                    break;

                case "Andersoft.Messaging.Abstractions.Abstractions.IMessageHandler<TMessage, TResult>":
                    results.Add(HandlerInfo.Handler(symbol.ToDisplayString(), args[0].ToDisplayString(), args[1].ToDisplayString()));
                    break;

                case "Andersoft.Messaging.Abstractions.Abstractions.IInterceptHandler<TMessage>":
                {
                    var open = args[0].TypeKind == TypeKind.TypeParameter;
                    results.Add(HandlerInfo.Interceptor(
                        open ? symbol.ConstructUnboundGenericType().ToDisplayString() : symbol.ToDisplayString(),
                        open ? string.Empty : args[0].ToDisplayString(),
                        result: null, isVoid: true, isOpen: open));
                    break;
                }

                case "Andersoft.Messaging.Abstractions.Abstractions.IInterceptHandler<TMessage, TResult>":
                {
                    var open = args[0].TypeKind == TypeKind.TypeParameter || args[1].TypeKind == TypeKind.TypeParameter;
                    results.Add(HandlerInfo.Interceptor(
                        open ? symbol.ConstructUnboundGenericType().ToDisplayString() : symbol.ToDisplayString(),
                        open ? string.Empty : args[0].ToDisplayString(),
                        result: open ? null : args[1].ToDisplayString(), isVoid: false, isOpen: open));
                    break;
                }
            }
        }

        return results.ToImmutable();
    }

    private static bool ExtendsSaga(INamedTypeSymbol symbol)
    {
        for (var b = symbol.BaseType; b is not null; b = b.BaseType)
            if (IsSagaBase(b))
                return true;
        return false;
    }

    // Compare against the unbound generic name so the match is independent of the base
    // class's type-parameter name (the real Saga&lt;TSagaState&gt; vs a stub's Saga&lt;TState&gt;).
    private static bool IsSagaBase(INamedTypeSymbol type) =>
        type.IsGenericType &&
        type.ConstructUnboundGenericType().ToDisplayString() == "Andersoft.Messaging.Abstractions.Abstractions.Saga<>";

    private static SagaInfo? GetSagaType(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return null;

        INamedTypeSymbol? sagaBase = null;
        for (var b = symbol.BaseType; b is not null; b = b.BaseType)
        {
            if (IsSagaBase(b))
            {
                sagaBase = b;
                break;
            }
        }

        if (sagaBase is null) return null;

        var info = new SagaInfo(symbol.ToDisplayString(), sagaBase.TypeArguments[0].ToDisplayString());

        // Event types come from the MapStartedBy/MapHandledBy calls in ConfigureHowToFindSaga.
        foreach (var member in symbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            if (method.Name != "ConfigureHowToFindSaga" || method.MethodKind != MethodKind.Ordinary) continue;

            foreach (var syntaxRef in method.DeclaringSyntaxReferences)
            {
                if (syntaxRef.GetSyntax(ct) is not MethodDeclarationSyntax ms || ms.Body is null) continue;

                foreach (var node in ms.Body.DescendantNodes())
                {
                    if (node is not InvocationExpressionSyntax inv) continue;
                    var expr = inv.Expression.ToString();
                    if (!expr.Contains("MapStartedBy") && !expr.Contains("MapHandledBy")) continue;

                    // Resolve the type arguments semantically so the event type is fully qualified —
                    // the generated registration has no per-feature usings. TEvent is the first of the
                    // two type arguments (<TEvent, TKey>).
                    if (context.SemanticModel.GetSymbolInfo(inv, ct).Symbol is IMethodSymbol m
                        && m.TypeArguments.Length >= 1)
                    {
                        info.EventTypes.Add(m.TypeArguments[0].ToDisplayString());
                    }

                    // The second argument is the saga-key selector (s => s.Field). Capture the field
                    // name so a unique index can be emitted for it. Only direct member access on the
                    // lambda parameter yields an indexable field; anything else is skipped.
                    if (inv.ArgumentList.Arguments.Count >= 2 &&
                        ExtractSimpleMemberName(inv.ArgumentList.Arguments[1].Expression) is { } field)
                    {
                        info.KeyFields.Add(field);
                    }
                }
            }
        }

        return info;
    }

    // ── Dispatcher generation ──────────────────────────────────────────

    private static string GenerateDispatcher(ImmutableArray<HandlerInfo> all, IReadOnlyList<SagaInfo> sagas)
    {
        var handlers = all.Where(h => !h.IsInterceptor).ToList();
        var interceptors = all.Where(h => h.IsInterceptor).ToList();

        // Messages that return a value — single dispatch.
        var resultMessages = handlers.Where(h => h.ResultType is not null)
            .GroupBy(h => h.MessageType)
            .Select(g => new ResultMessage(g.Key, g.First().ResultType!))
            .ToList();

        // Void messages — dispatched to all handlers. Saga events are void messages whose
        // only handler is the registered SagaDispatcher.
        var voidMessages = handlers.Where(h => h.ResultType is null).Select(h => h.MessageType)
            .Concat(sagas.SelectMany(s => s.EventTypes))
            .Distinct()
            .ToList();

        var hasOpenResultInterceptor = interceptors.Any(i => i.IsOpenGeneric && !i.IsVoidInterceptor);
        var hasOpenVoidInterceptor = interceptors.Any(i => i.IsOpenGeneric && i.IsVoidInterceptor);
        var closedResultInterceptors = interceptors.Where(i => !i.IsOpenGeneric && !i.IsVoidInterceptor)
            .Select(i => i.MessageType).ToImmutableHashSet();
        var closedVoidInterceptors = interceptors.Where(i => !i.IsOpenGeneric && i.IsVoidInterceptor)
            .Select(i => i.MessageType).ToImmutableHashSet();

        bool ResultIntercepted(string msg) => hasOpenResultInterceptor || closedResultInterceptors.Contains(msg);
        bool VoidIntercepted(string msg) => hasOpenVoidInterceptor || closedVoidInterceptors.Contains(msg);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Andersoft.Messaging.Abstractions;");
        sb.AppendLine("using Andersoft.Messaging.Abstractions.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace Andersoft.Messaging.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("public sealed class TypedDispatcher");
        sb.AppendLine("{");

        // Fields
        foreach (var m in resultMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m.Message));
            sb.AppendLine($"    private readonly IMessageHandler<{m.Message}, {m.Result}> _{camel}Handler;");
            if (ResultIntercepted(m.Message))
                sb.AppendLine($"    private readonly System.Collections.Generic.List<IInterceptHandler<{m.Message}, {m.Result}>> _{camel}Interceptors;");
        }
        foreach (var m in voidMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m));
            sb.AppendLine($"    private readonly System.Collections.Generic.List<IMessageHandler<{m}>> _{camel}Handlers;");
            if (VoidIntercepted(m))
                sb.AppendLine($"    private readonly System.Collections.Generic.List<IInterceptHandler<{m}>> _{camel}Interceptors;");
        }

        // Constructor
        sb.AppendLine();
        sb.AppendLine("    public TypedDispatcher(");
        var ps = new List<string>();
        foreach (var m in resultMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m.Message));
            ps.Add($"        IMessageHandler<{m.Message}, {m.Result}> {camel}Handler");
            if (ResultIntercepted(m.Message))
                ps.Add($"        System.Collections.Generic.IEnumerable<IInterceptHandler<{m.Message}, {m.Result}>> {camel}Interceptors");
        }
        foreach (var m in voidMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m));
            ps.Add($"        System.Collections.Generic.IEnumerable<IMessageHandler<{m}>> {camel}Handlers");
            if (VoidIntercepted(m))
                ps.Add($"        System.Collections.Generic.IEnumerable<IInterceptHandler<{m}>> {camel}Interceptors");
        }
        sb.AppendLine(string.Join(",\n", ps) + ")");
        sb.AppendLine("    {");
        foreach (var m in resultMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m.Message));
            sb.AppendLine($"        _{camel}Handler = {camel}Handler;");
            if (ResultIntercepted(m.Message))
                sb.AppendLine($"        _{camel}Interceptors = System.Linq.Enumerable.ToList({camel}Interceptors ?? System.Array.Empty<IInterceptHandler<{m.Message}, {m.Result}>>());");
        }
        foreach (var m in voidMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m));
            sb.AppendLine($"        _{camel}Handlers = System.Linq.Enumerable.ToList({camel}Handlers ?? System.Array.Empty<IMessageHandler<{m}>>());");
            if (VoidIntercepted(m))
                sb.AppendLine($"        _{camel}Interceptors = System.Linq.Enumerable.ToList({camel}Interceptors ?? System.Array.Empty<IInterceptHandler<{m}>>());");
        }
        sb.AppendLine("    }");

        // Result dispatch — single handler, optional interceptor chain
        foreach (var m in resultMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m.Message));
            sb.AppendLine();
            sb.AppendLine($"    public System.Threading.Tasks.ValueTask<{m.Result}> DispatchAsync(");
            sb.AppendLine($"        {m.Message} message,");
            sb.AppendLine("        System.Threading.CancellationToken ct = default)");
            if (ResultIntercepted(m.Message))
            {
                sb.AppendLine("    {");
                sb.AppendLine($"        return ChainInterceptors(_{camel}Interceptors, message, () => _{camel}Handler.HandleAsync(message, ct), ct);");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"        => _{camel}Handler.HandleAsync(message, ct);");
            }
        }

        // Void dispatch — fan-out to all handlers, optional interceptor chain
        foreach (var m in voidMessages)
        {
            var camel = ToCamelCase(ExtractShortName(m));
            sb.AppendLine();
            sb.AppendLine("    public System.Threading.Tasks.ValueTask DispatchAsync(");
            sb.AppendLine($"        {m} message,");
            sb.AppendLine("        System.Threading.CancellationToken ct = default)");
            if (VoidIntercepted(m))
            {
                sb.AppendLine("    {");
                sb.AppendLine($"        return ChainInterceptors(_{camel}Interceptors, message, () => InvokeAll(_{camel}Handlers, message, ct), ct);");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"        => InvokeAll(_{camel}Handlers, message, ct);");
            }
        }

        // Catch-all for void messages known only as a base type / object.
        if (voidMessages.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    public System.Threading.Tasks.ValueTask DispatchAsync(");
            sb.AppendLine("        object message,");
            sb.AppendLine("        System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        => message switch");
            sb.AppendLine("        {");
            foreach (var m in voidMessages)
                sb.AppendLine($"            {m} e => DispatchAsync(e, ct),");
            sb.AppendLine("            _ => default,");
            sb.AppendLine("        };");
        }

        // Helpers — emitted only when used.
        if (resultMessages.Any(m => ResultIntercepted(m.Message)))
        {
            sb.AppendLine();
            sb.AppendLine("    private static System.Threading.Tasks.ValueTask<TResult> ChainInterceptors<TMessage, TResult>(");
            sb.AppendLine("        System.Collections.Generic.List<IInterceptHandler<TMessage, TResult>> interceptors,");
            sb.AppendLine("        TMessage message,");
            sb.AppendLine("        RequestHandlerDelegate<TResult> handler,");
            sb.AppendLine("        System.Threading.CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        RequestHandlerDelegate<TResult> next = handler;");
            sb.AppendLine("        for (var i = interceptors.Count - 1; i >= 0; i--)");
            sb.AppendLine("        {");
            sb.AppendLine("            var interceptor = interceptors[i];");
            sb.AppendLine("            var current = next;");
            sb.AppendLine("            next = () => interceptor.HandleAsync(message, current, ct);");
            sb.AppendLine("        }");
            sb.AppendLine("        return next();");
            sb.AppendLine("    }");
        }

        if (voidMessages.Any(VoidIntercepted))
        {
            sb.AppendLine();
            sb.AppendLine("    private static System.Threading.Tasks.ValueTask ChainInterceptors<TMessage>(");
            sb.AppendLine("        System.Collections.Generic.List<IInterceptHandler<TMessage>> interceptors,");
            sb.AppendLine("        TMessage message,");
            sb.AppendLine("        RequestHandlerDelegate handler,");
            sb.AppendLine("        System.Threading.CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        RequestHandlerDelegate next = handler;");
            sb.AppendLine("        for (var i = interceptors.Count - 1; i >= 0; i--)");
            sb.AppendLine("        {");
            sb.AppendLine("            var interceptor = interceptors[i];");
            sb.AppendLine("            var current = next;");
            sb.AppendLine("            next = () => interceptor.HandleAsync(message, current, ct);");
            sb.AppendLine("        }");
            sb.AppendLine("        return next();");
            sb.AppendLine("    }");
        }

        if (voidMessages.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    private static async System.Threading.Tasks.ValueTask InvokeAll<TMessage>(");
            sb.AppendLine("        System.Collections.Generic.List<IMessageHandler<TMessage>> handlers,");
            sb.AppendLine("        TMessage message,");
            sb.AppendLine("        System.Threading.CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        foreach (var handler in handlers)");
            sb.AppendLine("            await handler.HandleAsync(message, ct);");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Registration generation ────────────────────────────────────────

    private static string GenerateRegistration(ImmutableArray<HandlerInfo> all, IReadOnlyList<SagaInfo> sagas)
    {
        var handlers = all.Where(h => !h.IsInterceptor).ToList();
        var interceptors = all.Where(h => h.IsInterceptor).ToList();
        var hasSagas = sagas.Count > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Andersoft.Messaging.Abstractions;");
        sb.AppendLine("using Andersoft.Messaging.Abstractions.Abstractions;");
        if (hasSagas) sb.AppendLine("using Andersoft.Messaging.Abstractions.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace Andersoft.Messaging.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("public static class HandlerRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddApplicationHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var h in handlers)
        {
            var iface = h.ResultType is null
                ? $"IMessageHandler<{h.MessageType}>"
                : $"IMessageHandler<{h.MessageType}, {h.ResultType}>";
            sb.AppendLine($"        services.AddScoped<{iface}, {h.HandlerType}>();");
        }

        foreach (var i in interceptors)
        {
            if (i.IsOpenGeneric)
            {
                var openIface = i.IsVoidInterceptor ? "typeof(IInterceptHandler<>)" : "typeof(IInterceptHandler<,>)";
                sb.AppendLine($"        services.AddScoped({openIface}, typeof({i.HandlerType}));");
            }
            else
            {
                var iface = i.IsVoidInterceptor
                    ? $"IInterceptHandler<{i.MessageType}>"
                    : $"IInterceptHandler<{i.MessageType}, {i.ResultType}>";
                sb.AppendLine($"        services.AddScoped<{iface}, {i.HandlerType}>();");
            }
        }

        if (hasSagas)
        {
            sb.AppendLine();
            sb.AppendLine("        // Sagas — coordinators over a grouping of message handlers.");
            sb.AppendLine("        // The configure callback wires a DEFERRED TypedDispatcher factory into the");
            sb.AppendLine("        // saga's generated Saga<TState> base (see SagaBase.g.cs). It must stay deferred:");
            sb.AppendLine("        // the dispatcher's fan-out includes this saga, so resolving it eagerly here would");
            sb.AppendLine("        // form a DI construction cycle.");
            foreach (var s in sagas)
            {
                sb.AppendLine($"        services.AddSaga<{s.SagaType}, {s.StateType}>(");
                sb.AppendLine("            static (saga, sp) => saga.DispatcherFactory = () => sp.GetRequiredService<TypedDispatcher>());");
            }

            var eventTypes = sagas.SelectMany(s => s.EventTypes).Distinct().ToList();
            if (eventTypes.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // Saga dispatchers join each event's handler fan-out");
                foreach (var ev in eventTypes)
                {
                    sb.AppendLine($"        services.AddScoped<IMessageHandler<{ev}>>(sp =>");
                    sb.AppendLine($"            new Andersoft.Messaging.Abstractions.EntityFrameworkCore.SagaDispatcher<{ev}>(");
                    sb.AppendLine($"                sp.GetRequiredService<System.Collections.Generic.IEnumerable<Andersoft.Messaging.Abstractions.Abstractions.Saga>>()));");
                }
            }
        }

        sb.AppendLine("        services.AddScoped<TypedDispatcher>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        if (hasSagas)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Maps every saga state type (key on Id, Version as concurrency token) and adds a unique");
            sb.AppendLine("    /// index for each correlation field used in <c>ConfigureHowToFindSaga</c>.");
            sb.AppendLine("    /// Call from <c>OnModelCreating</c>.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static Microsoft.EntityFrameworkCore.ModelBuilder ApplySagaConfigurations(this Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)");
            sb.AppendLine("    {");
            foreach (var group in sagas.GroupBy(s => s.StateType))
            {
                sb.AppendLine($"        modelBuilder.ConfigureSagaState<{group.Key}>();");
                foreach (var field in group.SelectMany(s => s.KeyFields).Distinct())
                    sb.AppendLine($"        modelBuilder.Entity<{group.Key}>().HasIndex(static x => x.{field}).IsUnique();");
            }
            sb.AppendLine("        return modelBuilder;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Saga merge ─────────────────────────────────────────────────────

    /// <summary>
    /// Collapses the per-declaration <see cref="SagaInfo"/> values into one per saga type, unioning
    /// the event types discovered across (the uncommon case of) multiple partial declarations.
    /// </summary>
    private static IReadOnlyList<SagaInfo> MergeSagas(ImmutableArray<SagaInfo> sagas)
    {
        var merged = new List<SagaInfo>();
        foreach (var group in sagas.GroupBy(s => s.SagaType))
        {
            var info = new SagaInfo(group.Key, group.First().StateType);
            foreach (var ev in group.SelectMany(s => s.EventTypes).Distinct())
                info.EventTypes.Add(ev);
            foreach (var field in group.SelectMany(s => s.KeyFields).Distinct())
                info.KeyFields.Add(field);
            merged.Add(info);
        }
        return merged;
    }

    /// <summary>
    /// Extracts the field name from a simple saga-key selector — <c>s =&gt; s.Field</c> yields
    /// <c>Field</c>. Returns null for anything that is not a direct member access on the lambda
    /// parameter (nested access, method calls, etc.), which cannot back a unique index.
    /// </summary>
    private static string? ExtractSimpleMemberName(ExpressionSyntax expression)
    {
        var body = expression switch
        {
            SimpleLambdaExpressionSyntax s => s.Body,
            ParenthesizedLambdaExpressionSyntax p => p.Body,
            _ => null,
        };

        return body is MemberAccessExpressionSyntax { Expression: IdentifierNameSyntax } ma
            ? ma.Name.Identifier.Text
            : null;
    }

    private static string ToCamelCase(string s)
    {
        if (string.IsNullOrEmpty(s) || char.IsLower(s[0]))
            return s;
        return char.ToLowerInvariant(s[0]) + s.Substring(1);
    }

    private static string ExtractShortName(string fullTypeName)
    {
        var lastDot = fullTypeName.LastIndexOf('.');
        return lastDot >= 0 ? fullTypeName.Substring(lastDot + 1) : fullTypeName;
    }

    private sealed class HandlerInfo
    {
        public bool IsInterceptor { get; private set; }
        public string HandlerType { get; private set; } = string.Empty;
        public string MessageType { get; private set; } = string.Empty;
        public string? ResultType { get; private set; }
        public bool IsVoidInterceptor { get; private set; }
        public bool IsOpenGeneric { get; private set; }

        public static HandlerInfo Handler(string handlerType, string messageType, string? result) => new()
        {
            IsInterceptor = false,
            HandlerType = handlerType,
            MessageType = messageType,
            ResultType = result,
        };

        public static HandlerInfo Interceptor(string handlerType, string messageType, string? result, bool isVoid, bool isOpen) => new()
        {
            IsInterceptor = true,
            HandlerType = handlerType,
            MessageType = messageType,
            ResultType = result,
            IsVoidInterceptor = isVoid,
            IsOpenGeneric = isOpen,
        };
    }

    private sealed class ResultMessage
    {
        public string Message { get; }
        public string Result { get; }
        public ResultMessage(string message, string result) { Message = message; Result = result; }
    }

    private sealed class SagaInfo
    {
        public string SagaType { get; }
        public string StateType { get; }
        public List<string> EventTypes { get; } = new();

        /// <summary>Saga-state field names used as correlation keys; each gets a unique index.</summary>
        public List<string> KeyFields { get; } = new();

        public SagaInfo(string sagaType, string stateType)
        {
            SagaType = sagaType;
            StateType = stateType;
        }
    }
}
